### ISSUE TITLE
Same as code points?

### ISSUE THREAD

**Issue by wshager** [lemire/FastIntegerCompression.js#1]
I'm surprised that the output buffer of a compressed code-point array has the same byte size as the uncompressed string. I assume that means that if I encode an array of integers as a UTF-8 string it would result in the same size. 

```javascript
function lengthInUtf8Bytes(str) {
  var m = encodeURIComponent(str).match(/%[89ABab]/g);
  return str.length + (m ? m.length : 0);
}
FastIntCompression.compress(str.split("").map(_ => _.codePointAt(0))) == lengthInUtf8Bytes(str)
```

**Comment by wshager** [comment]
It seems the compression is only noticeable for arrays with higher values:

```javascript
FastIntCompression.compress(array).byteLength > lengthInUtf8Bytes(array.map(_ => String.fromCodePoint(_)))
```

**Comment by wshager** [comment]
Anyway, it seems this algorithm doesn't do well enough for string compression. On the higher unicode planes I get some 50% reduction, but latin1 just stays the same. The js library lz-string does a lot better (not sure of the performance).

**Comment by lemire** [comment]
I have added a benchmark. Please check the README.

**Comment by wshager** [comment]
@lemire it's fast, but my point was that the size of a compressed codepoint array is exactly the same as the size on disk of the ASCII text file when serialized. AFAICT this means compression is max 25% when serialized.

**Comment by wshager** [comment]
@lemire just to be complete, FastIntCompression is around 20 times faster than native `Buffer.from(String.fromCodePoint.apply(null,array))`, with an average 75% higher compression rate. This was interesting to me for cases where integer size wouldn't exceed 17*2^16. But perhaps I'm not making sense at all.

**Comment by lemire** [comment]
In which context would you do `Buffer.from(String.fromCodePoint.apply(null,array))`?

**Comment by wshager** [comment]
@lemire I don't know, I was thinking from a text perspective... I don't know enough about buffers.

**Comment by wshager** [comment]
@lemire I assume Node does some internal shuffling to fit utf-8. Here is a browser compatible version: https://github.com/feross/buffer/blob/master/index.js#L1670. How is it different from your code?

**Comment by lemire** [comment]
The code you point to is similar in spirit. Of course, the library compresses integers, not unicode strings.

**Comment by r03ert0** [comment]
hello,
I tried to compress an array with 10,000 values, all zeros (for testing). The resulting buffer size was 10000 bytes long... I think I was expecting some other type of compression... am I right that the aim of the library is to compress the representation of integers in a buffer more that reducing redundancy, etc?

**Comment by lemire** [comment]
Given that JavaScript uses 64-bit values (8 bytes), using only 1 byte per value is 1:8 compression. Obviously, in the scenario you describe, the compression ratio could be much higher. We could implement other schemes, but the current library just supports VByte.
