### ISSUE TITLE
computeHowManyIntegers returns unexpected result

### ISSUE THREAD

**Issue by jjhvlabs** [lemire/FastIntegerCompression.js#11]
hi, first off, thanks for sharing this!
for me the computeHowManyIntegers doesn't seem to work:
if you change this line
[testline](https://github.com/lemire/FastIntegerCompression.js/blob/033768f72e69ea4e33f8d29fca7cf516e0c5356b/unit/basictests.js#L20)
to
`if(FastIntegerCompression.computeHowManyIntegers(buf) !== array.length) throw "bad count";`
it will show

**Comment by lemire** [comment]
Thanks for the report, please update to version 0.1.0.
