### ISSUE TITLE
Handle negative/floating point

### ISSUE THREAD

**Issue by wshager** [lemire/FastIntegerCompression.js#3]
What would be the best way to compress negative and floating point numbers?

**Comment by TheGreatRambler** [comment]
Im having the same problem!!! No wonder it isnt working!

**Comment by lemire** [comment]
For negative integers, you might want to use zigzag encoding...

```
zigzag_encode:
	val => (val + val) ^ (val >>> 31);


zigzag_decode:
	val => (val >>> 1) ^ -(val & 1);
}
```

If someone is interested in zigzag encoding, pull requests are invited.


Given that the library is called "FastIntegerCompression", I don't think one should expect it to support non-integer values.

**Comment by TheGreatRambler** [comment]
Yeah, I am multiplying positive values by 2 and multiplying negative values by -2 and adding one and it works.

**Comment by lemire** [comment]
Fixed in latest release.

I am going to close this even though we have no support for floating point numbers. Floats are out-of-scope at this time.
